version: "3"

services:
  ts-accounts:
    build:
      context: ./ts-accounts
    image: ts-accounts:stand
    ports:
      - "8089:8089"

  ts-transactions:
    build:
      context: ./ts-transactions
    image: ts-transactions:stand
    ports:
      - "8090:8090"

  ts-reports:
    build:
      context: ./ts-reports
    image: ts-reports:stand
    ports:
      - "8091:8091"
