spring.datasource.url=jdbc:postgresql://host.docker.internal:5436/ts-reports

ru.klokov.tssystem.accounts.url=http://host.docker.internal:8089/api/v1/common/bank_accounts
ru.klokov.tssystem.transactions.url=http://host.docker.internal:8090/api/v1/common/transactions
ru.klokov.tssystem.users.url=http://host.docker.internal:8089/api/v1/common/users
