version: '3'

services:
  build-agent:
    build: .
    container_name: test-build-agent
    environment:
      - AZP_URL
      - AZP_POOL
      - AZP_AGENT_NAME
      - AZP_TOKEN
    user: "1000:1000"
