FROM eclipse-temurin:17-jre
WORKDIR /app
COPY target/*.jar app.jar

ENV JAVA_TOOL_OPTIONS=""
ENV SPRING_PROFILES_ACTIVE=stand

EXPOSE 8091
ENTRYPOINT ["sh","-c","exec java $JAVA_TOOL_OPTIONS -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar app.jar"]
